import React from 'react'
import Hero from '../../components/website/Hero'
import Categry from '../../components/website/home/Categry'
import Selles from '../../components/website/home/Selles'
import NewProduct from '../../components/website/home/NewArrival'
import Featured from '../../components/website/home/Featured'
import Service from '../../components/website/home/Service'
import Review from '../../components/website/home/Review'
import Banner from '../../components/website/home/Banner'
import { fetchCategory } from '@/utils/api'   // ✅ spelling fixed

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function page() {
  const catagries = await fetchCategory({ status: true });

  return (
    <div className='w-full bg-[#F8F5F1] pt-4 sm:pt-6 px-4 sm:px-6 pb-5'>
      <Hero
        subtitle="Summer Collection 2026"
        title1="Where Comfort"
        title2="Meets"
        highlight="Craft"
        description1="Scandinavian-inspired furniture for modern living."
        bgColor="#2C2016"
        image="/hero/hero1.png"
      />
      <Categry catagries={catagries.data} />
      <Selles />
      <NewProduct />
      <Featured />
      <Service />
      <Review />
      <Banner />
    </div>
  )
}
