import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/admin/Sidebar";
import Header from "@/components/admin/Header";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full overflow-hidden">
        <Toaster position="top-right" richColors toastOptions={{ duration: 700 }} />
        <div className="w-full flex h-full">
          <Sidebar />
          {/* Right panel: flex column to stack header and content */}
          <div className="flex-1 flex flex-col min-h-0">
            <Header />
            {/* Main content area with independent scrolling */}
            <main className="flex-1 overflow-y-auto bg-[#f6f8fc]">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}