import Aside from "@/components/website/store/Aside";
import Hero from "@/components/website/Hero";
import Store_Hrader from "@/components/website/store/Store_Hrader";
import { fetchProduct } from "@/utils/api";

export const metadata = {
  title: "Store Page",
  description: "Generated by create next app",
};

export default async function StoreLayout({ children, searchParams }) {
  const params = await (searchParams || Promise.resolve({}));
  const countRes = await fetchProduct({
    rooms:    params?.rooms    || "",
    category: params?.category || "",
    limit:    1000,
    ...(params?.stock !== "" && params?.stock ? { stock: params.stock } : {}),
    ...(params?.color !== "" && params?.color ? { color: params.color } : {}),
  });
  const productCount = countRes?.data?.length ?? 0;

  return (
    <div className="w-full bg-[#F8F5F1] pt-4 sm:pt-6 pb-5">
      <div className="max-w-container mx-auto px-4 sm:px-6">
        <Hero
          subtitle="New Collection - ss 2026"
          title1="Modern Living"
          title2=""
          highlight="Collection"
          description1="Timeless furniture crafted for elegant spaces."
          description2="Designed with intention, built to endure."
          bgColor="#2C2016"
          image="/hero/hero1.png"
        />
        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-6 mt-6">
          <Aside />
          <div>
            <Store_Hrader count={productCount} />
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}